language: node_js
node_js:
  - "0.10"
deploy:
  provider: heroku
  api_key: jwVjOqa/pJlFAmssZnyaGXb1Mwe25PRbiQGPk3A8pVfBBluF7mkv+wotUDGTrCwd6ch/iZR8CyAGtUo2Ezqo6B4+gAJ+HLiSbYzVvbJJayWAGMxHS0mbP9Eom07cSbUdb9hRw9GtBdqRyK3D8/hIudDUTRoR6AAhalhdEh8xNb8=
  app: uuid-validator
