language: node_js
node_js: 
- "0.10"
deploy: 
  provider: heroku
  api_key: 
    secure: WikZlStuhAe1lZ5bnshbnK52TPbM3uoummlLXG2lgvfZZIhnbmnYKby3hhbGJnMEaLdO3Triq7B5z2w8dK8P45X5cQcYegkJaZgFJIlviH8E0RsaTNNU6RNw1hkLklN7ROxUHFFjU+MhjLN1RIkkg7mcsVTYQVLskT180rAy29Q=
  app: uuid-validator
  "on": 
    repo: richet/uuid-validator
